// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteOpenAIAPIKey() {
  return window['go']['app']['App']['DeleteOpenAIAPIKey']();
}

export function GetFiles() {
  return window['go']['app']['App']['GetFiles']();
}

export function GetFilesInDirectory(arg1) {
  return window['go']['app']['App']['GetFilesInDirectory'](arg1);
}

export function GetOpenAIAPIKey() {
  return window['go']['app']['App']['GetOpenAIAPIKey']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function PickFile() {
  return window['go']['app']['App']['PickFile']();
}

export function ProcessFile(arg1) {
  return window['go']['app']['App']['ProcessFile'](arg1);
}

export function ProcessFileForTranscription(arg1, arg2) {
  return window['go']['app']['App']['ProcessFileForTranscription'](arg1, arg2);
}

export function ReadFileContent(arg1) {
  return window['go']['app']['App']['ReadFileContent'](arg1);
}

export function SaveOpenAIAPIKey(arg1) {
  return window['go']['app']['App']['SaveOpenAIAPIKey'](arg1);
}
