// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {models} from '../models';

export function DeleteOpenAIAPIKey():Promise<app.APIKeyResult>;

export function GetAllInterviewAnalyticsAPI(arg1:string,arg2:string):Promise<Array<models.InterviewAnalytics>>;

export function GetFiles():Promise<Array<app.FileInfo>>;

export function GetFilesInDirectory(arg1:string):Promise<Array<app.FileInfo>>;

export function GetGlobalAnalyticsAPI(arg1:string,arg2:string):Promise<models.GlobalAnalytics>;

export function GetInputDevices():Promise<app.DeviceResult>;

export function GetInterviewAnalyticsAPI(arg1:number):Promise<models.InterviewAnalytics>;

export function GetOpenAIAPIKey():Promise<app.APIKeyResult>;

export function GetRecordingStatus():Promise<app.RecordingResult>;

export function GetWebSocketURL():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function PickFile():Promise<string>;

export function ProcessFile(arg1:string):Promise<app.FileInfo>;

export function ProcessFileForCallAnalysis(arg1:string):Promise<app.CallAnalysisResult>;

export function ProcessFileForTranscription(arg1:string):Promise<app.TranscriptionResult>;

export function ReadFileContent(arg1:string):Promise<app.FileContent>;

export function SaveAndProcessRecording(arg1:string):Promise<app.TranscriptionResult>;

export function SaveAndProcessRecordingForCall(arg1:string):Promise<app.CallAnalysisResult>;

export function SaveOpenAIAPIKey(arg1:string):Promise<app.APIKeyResult>;

export function SaveRecording(arg1:string):Promise<app.RecordingResult>;

export function SetAudioInputDevice(arg1:string):Promise<app.DeviceResult>;

export function StartAudioRecording():Promise<app.RecordingResult>;

export function StopAudioRecording():Promise<app.RecordingResult>;
