// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetFiles():Promise<Array<app.FileInfo>>;

export function GetFilesInDirectory(arg1:string):Promise<Array<app.FileInfo>>;

export function Greet(arg1:string):Promise<string>;

export function ProcessFile(arg1:string):Promise<app.FileInfo>;

export function ReadFileContent(arg1:string):Promise<app.FileContent>;
