// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteOpenAIAPIKey() {
  return window['go']['app']['App']['DeleteOpenAIAPIKey']();
}

export function GetAllInterviewAnalyticsAPI(arg1, arg2) {
  return window['go']['app']['App']['GetAllInterviewAnalyticsAPI'](arg1, arg2);
}

export function GetFiles() {
  return window['go']['app']['App']['GetFiles']();
}

export function GetFilesInDirectory(arg1) {
  return window['go']['app']['App']['GetFilesInDirectory'](arg1);
}

export function GetGlobalAnalyticsAPI(arg1, arg2) {
  return window['go']['app']['App']['GetGlobalAnalyticsAPI'](arg1, arg2);
}

export function GetInputDevices() {
  return window['go']['app']['App']['GetInputDevices']();
}

export function GetInterviewAnalyticsAPI(arg1) {
  return window['go']['app']['App']['GetInterviewAnalyticsAPI'](arg1);
}

export function GetOpenAIAPIKey() {
  return window['go']['app']['App']['GetOpenAIAPIKey']();
}

export function GetRecordingStatus() {
  return window['go']['app']['App']['GetRecordingStatus']();
}

export function GetWebSocketURL() {
  return window['go']['app']['App']['GetWebSocketURL']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function PickFile() {
  return window['go']['app']['App']['PickFile']();
}

export function ProcessFile(arg1) {
  return window['go']['app']['App']['ProcessFile'](arg1);
}

export function ProcessFileForCallAnalysis(arg1) {
  return window['go']['app']['App']['ProcessFileForCallAnalysis'](arg1);
}

export function ProcessFileForTranscription(arg1) {
  return window['go']['app']['App']['ProcessFileForTranscription'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['app']['App']['ReadFileContent'](arg1);
}

export function SaveAndProcessRecording(arg1) {
  return window['go']['app']['App']['SaveAndProcessRecording'](arg1);
}

export function SaveAndProcessRecordingForCall(arg1) {
  return window['go']['app']['App']['SaveAndProcessRecordingForCall'](arg1);
}

export function SaveOpenAIAPIKey(arg1) {
  return window['go']['app']['App']['SaveOpenAIAPIKey'](arg1);
}

export function SaveRecording(arg1) {
  return window['go']['app']['App']['SaveRecording'](arg1);
}

export function SetAudioInputDevice(arg1) {
  return window['go']['app']['App']['SetAudioInputDevice'](arg1);
}

export function StartAudioRecording() {
  return window['go']['app']['App']['StartAudioRecording']();
}

export function StopAudioRecording() {
  return window['go']['app']['App']['StopAudioRecording']();
}
