// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFiles() {
  return window['go']['app']['App']['GetFiles']();
}

export function GetFilesInDirectory(arg1) {
  return window['go']['app']['App']['GetFilesInDirectory'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function ProcessFile(arg1) {
  return window['go']['app']['App']['ProcessFile'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['app']['App']['ReadFileContent'](arg1);
}
