// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCallAPI(arg1) {
  return window['go']['wails_app']['App']['DeleteCallAPI'](arg1);
}

export function DeleteInterviewAPI(arg1) {
  return window['go']['wails_app']['App']['DeleteInterviewAPI'](arg1);
}

export function DeleteOpenAIAPIKey() {
  return window['go']['wails_app']['App']['DeleteOpenAIAPIKey']();
}

export function GetAllCallsAPI(arg1, arg2) {
  return window['go']['wails_app']['App']['GetAllCallsAPI'](arg1, arg2);
}

export function GetAllInterviewAnalyticsAPI(arg1, arg2) {
  return window['go']['wails_app']['App']['GetAllInterviewAnalyticsAPI'](arg1, arg2);
}

export function GetAllInterviewsAPI(arg1, arg2) {
  return window['go']['wails_app']['App']['GetAllInterviewsAPI'](arg1, arg2);
}

export function GetCallAPI(arg1) {
  return window['go']['wails_app']['App']['GetCallAPI'](arg1);
}

export function GetCallsByDateRangeAPI(arg1, arg2) {
  return window['go']['wails_app']['App']['GetCallsByDateRangeAPI'](arg1, arg2);
}

export function GetFiles() {
  return window['go']['wails_app']['App']['GetFiles']();
}

export function GetFilesInDirectory(arg1) {
  return window['go']['wails_app']['App']['GetFilesInDirectory'](arg1);
}

export function GetGlobalAnalyticsAPI(arg1, arg2) {
  return window['go']['wails_app']['App']['GetGlobalAnalyticsAPI'](arg1, arg2);
}

export function GetInputDevices() {
  return window['go']['wails_app']['App']['GetInputDevices']();
}

export function GetInterviewAPI(arg1) {
  return window['go']['wails_app']['App']['GetInterviewAPI'](arg1);
}

export function GetInterviewAnalyticsAPI(arg1) {
  return window['go']['wails_app']['App']['GetInterviewAnalyticsAPI'](arg1);
}

export function GetOpenAIAPIKey() {
  return window['go']['wails_app']['App']['GetOpenAIAPIKey']();
}

export function GetRecordingStatus() {
  return window['go']['wails_app']['App']['GetRecordingStatus']();
}

export function GetWebSocketURL() {
  return window['go']['wails_app']['App']['GetWebSocketURL']();
}

export function Greet(arg1) {
  return window['go']['wails_app']['App']['Greet'](arg1);
}

export function PickFile() {
  return window['go']['wails_app']['App']['PickFile']();
}

export function ProcessFile(arg1) {
  return window['go']['wails_app']['App']['ProcessFile'](arg1);
}

export function ProcessFileForCallAnalysis(arg1) {
  return window['go']['wails_app']['App']['ProcessFileForCallAnalysis'](arg1);
}

export function ProcessFileForTranscription(arg1) {
  return window['go']['wails_app']['App']['ProcessFileForTranscription'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['wails_app']['App']['ReadFileContent'](arg1);
}

export function SaveAndProcessRecording(arg1) {
  return window['go']['wails_app']['App']['SaveAndProcessRecording'](arg1);
}

export function SaveAndProcessRecordingForCall(arg1) {
  return window['go']['wails_app']['App']['SaveAndProcessRecordingForCall'](arg1);
}

export function SaveCallAPI(arg1) {
  return window['go']['wails_app']['App']['SaveCallAPI'](arg1);
}

export function SaveInterviewAPI(arg1) {
  return window['go']['wails_app']['App']['SaveInterviewAPI'](arg1);
}

export function SaveOpenAIAPIKey(arg1) {
  return window['go']['wails_app']['App']['SaveOpenAIAPIKey'](arg1);
}

export function SaveRecording(arg1) {
  return window['go']['wails_app']['App']['SaveRecording'](arg1);
}

export function SetAudioInputDevice(arg1) {
  return window['go']['wails_app']['App']['SetAudioInputDevice'](arg1);
}

export function StartAudioRecording() {
  return window['go']['wails_app']['App']['StartAudioRecording']();
}

export function StopAudioRecording() {
  return window['go']['wails_app']['App']['StopAudioRecording']();
}

export function UpdateCallAPI(arg1, arg2, arg3) {
  return window['go']['wails_app']['App']['UpdateCallAPI'](arg1, arg2, arg3);
}

export function UpdateCallAnalysisAPI(arg1, arg2) {
  return window['go']['wails_app']['App']['UpdateCallAnalysisAPI'](arg1, arg2);
}

export function UpdateInterviewAPI(arg1, arg2) {
  return window['go']['wails_app']['App']['UpdateInterviewAPI'](arg1, arg2);
}
