// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails_app} from '../models';
import {models} from '../models';

export function DeleteCallAPI(arg1:number):Promise<void>;

export function DeleteInterviewAPI(arg1:number):Promise<void>;

export function DeleteOpenAIAPIKey():Promise<wails_app.APIKeyResult>;

export function GetAllCallsAPI(arg1:number,arg2:number):Promise<Array<models.Call>>;

export function GetAllInterviewAnalyticsAPI(arg1:string,arg2:string):Promise<Array<models.InterviewAnalytics>>;

export function GetAllInterviewsAPI(arg1:string,arg2:string):Promise<Array<models.AnalyzeInterviewWithQA>>;

export function GetCallAPI(arg1:number):Promise<models.Call>;

export function GetCallsByDateRangeAPI(arg1:string,arg2:string):Promise<Array<models.Call>>;

export function GetFiles():Promise<Array<wails_app.FileInfo>>;

export function GetFilesInDirectory(arg1:string):Promise<Array<wails_app.FileInfo>>;

export function GetGlobalAnalyticsAPI(arg1:string,arg2:string):Promise<models.GlobalAnalytics>;

export function GetInputDevices():Promise<wails_app.DeviceResult>;

export function GetInterviewAPI(arg1:number):Promise<models.AnalyzeInterviewWithQA>;

export function GetInterviewAnalyticsAPI(arg1:number):Promise<models.InterviewAnalytics>;

export function GetOpenAIAPIKey():Promise<wails_app.APIKeyResult>;

export function GetRecordingStatus():Promise<wails_app.RecordingResult>;

export function GetWebSocketURL():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function PickFile():Promise<string>;

export function ProcessFile(arg1:string):Promise<wails_app.FileInfo>;

export function ProcessFileForCallAnalysis(arg1:string):Promise<wails_app.CallAnalysisResult>;

export function ProcessFileForTranscription(arg1:string):Promise<wails_app.TranscriptionResult>;

export function ReadFileContent(arg1:string):Promise<wails_app.FileContent>;

export function SaveAndProcessRecording(arg1:string):Promise<wails_app.TranscriptionResult>;

export function SaveAndProcessRecordingForCall(arg1:string):Promise<wails_app.CallAnalysisResult>;

export function SaveCallAPI(arg1:models.Call):Promise<models.Call>;

export function SaveInterviewAPI(arg1:models.AnalyzeInterviewWithQA):Promise<number>;

export function SaveOpenAIAPIKey(arg1:string):Promise<wails_app.APIKeyResult>;

export function SaveRecording(arg1:string):Promise<wails_app.RecordingResult>;

export function SetAudioInputDevice(arg1:string):Promise<wails_app.DeviceResult>;

export function StartAudioRecording():Promise<wails_app.RecordingResult>;

export function StopAudioRecording():Promise<wails_app.RecordingResult>;

export function UpdateCallAPI(arg1:number,arg2:string,arg3:any):Promise<void>;

export function UpdateCallAnalysisAPI(arg1:number,arg2:any):Promise<void>;

export function UpdateInterviewAPI(arg1:models.AnalyzeInterview,arg2:Array<models.QuestionAnswer>):Promise<void>;
