// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ProcessFile(arg1) {
  return window['go']['main']['App']['ProcessFile'](arg1);
}
