// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetFiles():Promise<Array<main.FileInfo>>;

export function Greet(arg1:string):Promise<string>;

export function ProcessFile(arg1:string):Promise<main.FileInfo>;
